config/routes.rb
Calendate::Application.routes.draw do
  resources :users
  post 'login' => 'sessions#login', as: :login
  post 'register' => 'users#create', as: :register

end

app/models/user.rb
class User < ActiveRecord::Base
  

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,			:presence					=> true,
  																	:length						=> { :maximum => 50 }
  validates :last_name,				:presence					=> true,
  																	:length						=> { :maximum => 50 }
  validates :email,					:presence					=> true,
  																	:format 			    => { :with => email_regex, message: "Incorrect email format."},
           													:uniqueness 			=> { :case_sensitive => false }

  validates :password,               :length           => { :within => 6..40 }



  has_secure_password
  attr_accessible :email_address, :first_name, :last_name, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end

 

  def create

      @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to profile_path
    else
      @show = "register"
      render action: "new"
    end


  end





  def delete
  end

  def show
  end

  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
Welcome To Smalendate! phong is the best






<%= simple_form_for @user, :url => login_path, :method => :post, :html => {:class => 'slide-toggle-left', :id => 'login_user'} do |f| %>
	<h1>Login</h1>
	<% if flash[:error] %>
		<p><%= flash[:error] %></p>
	<% end %>
  <%= f.input :email, label: 'Email' %>
  <%= f.input :password, label: 'Password' %>
  <%= f.button :submit, value:'Login', class: 'btn btn-primary'%>

<% end %>



or
<h1> User Create</h1>
<%= simple_form_for @user, :url => register_path, :method => :post, :html => {:class => 'slide-toggle-left'} do |f| %>
	<h1>Register</h1>
  <%= f.input :first_name, label: 'First Name' %>
  <%= f.input :last_name, label: 'Last Name' %>
  <%= f.input :email, label: 'Email' %>
  <%= f.input :password, label: 'Password' %>
  <%= f.input :password_confirmation, label: 'Confirm Password' %>
  <%= f.button :submit, value:'Register', class: 'btn btn-primary'%>
   <a href='#' id='login_link' class='clearfix'>Or Login</a>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>